//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace client.MyWs {
    using System.Diagnostics;
    using System;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System.Web.Services;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9221.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="MainServiceSoap", Namespace="http://tempuri.org/")]
    public partial class MainService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback UserGetOperationCompleted;
        
        private System.Threading.SendOrPostCallback UserAddOperationCompleted;
        
        private System.Threading.SendOrPostCallback UserDeleteOperationCompleted;
        
        private System.Threading.SendOrPostCallback UserUpdateOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetUserByPersonalDataOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAllUsersOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetUserWithEmailOperationCompleted;
        
        private System.Threading.SendOrPostCallback FoodItemGetOperationCompleted;
        
        private System.Threading.SendOrPostCallback FoodItemAddOperationCompleted;
        
        private System.Threading.SendOrPostCallback FoodItemUpdateOperationCompleted;
        
        private System.Threading.SendOrPostCallback FoodItemDeleteOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAllFoodItemsOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetFoodItemsOfCreatorOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetFoodItemByIdOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAllRolesOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetRoleFromIdOperationCompleted;
        
        private System.Threading.SendOrPostCallback RoleUpdateOperationCompleted;
        
        private System.Threading.SendOrPostCallback RoleAddOperationCompleted;
        
        private System.Threading.SendOrPostCallback AddItemToOrderOperationCompleted;
        
        private System.Threading.SendOrPostCallback AddOrderToHistoryOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateOrderedItemsOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateOrdersOperationCompleted;
        
        private System.Threading.SendOrPostCallback AddOrderedItemOperationCompleted;
        
        private System.Threading.SendOrPostCallback AddOrdersOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public MainService() {
            this.Url = global::client.Properties.Settings.Default.client_MyWs_MainService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event UserGetCompletedEventHandler UserGetCompleted;
        
        /// <remarks/>
        public event UserAddCompletedEventHandler UserAddCompleted;
        
        /// <remarks/>
        public event UserDeleteCompletedEventHandler UserDeleteCompleted;
        
        /// <remarks/>
        public event UserUpdateCompletedEventHandler UserUpdateCompleted;
        
        /// <remarks/>
        public event GetUserByPersonalDataCompletedEventHandler GetUserByPersonalDataCompleted;
        
        /// <remarks/>
        public event GetAllUsersCompletedEventHandler GetAllUsersCompleted;
        
        /// <remarks/>
        public event GetUserWithEmailCompletedEventHandler GetUserWithEmailCompleted;
        
        /// <remarks/>
        public event FoodItemGetCompletedEventHandler FoodItemGetCompleted;
        
        /// <remarks/>
        public event FoodItemAddCompletedEventHandler FoodItemAddCompleted;
        
        /// <remarks/>
        public event FoodItemUpdateCompletedEventHandler FoodItemUpdateCompleted;
        
        /// <remarks/>
        public event FoodItemDeleteCompletedEventHandler FoodItemDeleteCompleted;
        
        /// <remarks/>
        public event GetAllFoodItemsCompletedEventHandler GetAllFoodItemsCompleted;
        
        /// <remarks/>
        public event GetFoodItemsOfCreatorCompletedEventHandler GetFoodItemsOfCreatorCompleted;
        
        /// <remarks/>
        public event GetFoodItemByIdCompletedEventHandler GetFoodItemByIdCompleted;
        
        /// <remarks/>
        public event GetAllRolesCompletedEventHandler GetAllRolesCompleted;
        
        /// <remarks/>
        public event GetRoleFromIdCompletedEventHandler GetRoleFromIdCompleted;
        
        /// <remarks/>
        public event RoleUpdateCompletedEventHandler RoleUpdateCompleted;
        
        /// <remarks/>
        public event RoleAddCompletedEventHandler RoleAddCompleted;
        
        /// <remarks/>
        public event AddItemToOrderCompletedEventHandler AddItemToOrderCompleted;
        
        /// <remarks/>
        public event AddOrderToHistoryCompletedEventHandler AddOrderToHistoryCompleted;
        
        /// <remarks/>
        public event UpdateOrderedItemsCompletedEventHandler UpdateOrderedItemsCompleted;
        
        /// <remarks/>
        public event UpdateOrdersCompletedEventHandler UpdateOrdersCompleted;
        
        /// <remarks/>
        public event AddOrderedItemCompletedEventHandler AddOrderedItemCompleted;
        
        /// <remarks/>
        public event AddOrdersCompletedEventHandler AddOrdersCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UserGet", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public MyUser UserGet(int id) {
            object[] results = this.Invoke("UserGet", new object[] {
                        id});
            return ((MyUser)(results[0]));
        }
        
        /// <remarks/>
        public void UserGetAsync(int id) {
            this.UserGetAsync(id, null);
        }
        
        /// <remarks/>
        public void UserGetAsync(int id, object userState) {
            if ((this.UserGetOperationCompleted == null)) {
                this.UserGetOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUserGetOperationCompleted);
            }
            this.InvokeAsync("UserGet", new object[] {
                        id}, this.UserGetOperationCompleted, userState);
        }
        
        private void OnUserGetOperationCompleted(object arg) {
            if ((this.UserGetCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UserGetCompleted(this, new UserGetCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UserAdd", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int UserAdd(MyUser newUser) {
            object[] results = this.Invoke("UserAdd", new object[] {
                        newUser});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void UserAddAsync(MyUser newUser) {
            this.UserAddAsync(newUser, null);
        }
        
        /// <remarks/>
        public void UserAddAsync(MyUser newUser, object userState) {
            if ((this.UserAddOperationCompleted == null)) {
                this.UserAddOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUserAddOperationCompleted);
            }
            this.InvokeAsync("UserAdd", new object[] {
                        newUser}, this.UserAddOperationCompleted, userState);
        }
        
        private void OnUserAddOperationCompleted(object arg) {
            if ((this.UserAddCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UserAddCompleted(this, new UserAddCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UserDelete", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int UserDelete(MyUser userToDelete) {
            object[] results = this.Invoke("UserDelete", new object[] {
                        userToDelete});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void UserDeleteAsync(MyUser userToDelete) {
            this.UserDeleteAsync(userToDelete, null);
        }
        
        /// <remarks/>
        public void UserDeleteAsync(MyUser userToDelete, object userState) {
            if ((this.UserDeleteOperationCompleted == null)) {
                this.UserDeleteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUserDeleteOperationCompleted);
            }
            this.InvokeAsync("UserDelete", new object[] {
                        userToDelete}, this.UserDeleteOperationCompleted, userState);
        }
        
        private void OnUserDeleteOperationCompleted(object arg) {
            if ((this.UserDeleteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UserDeleteCompleted(this, new UserDeleteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UserUpdate", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int UserUpdate(MyUser userToUpdate) {
            object[] results = this.Invoke("UserUpdate", new object[] {
                        userToUpdate});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void UserUpdateAsync(MyUser userToUpdate) {
            this.UserUpdateAsync(userToUpdate, null);
        }
        
        /// <remarks/>
        public void UserUpdateAsync(MyUser userToUpdate, object userState) {
            if ((this.UserUpdateOperationCompleted == null)) {
                this.UserUpdateOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUserUpdateOperationCompleted);
            }
            this.InvokeAsync("UserUpdate", new object[] {
                        userToUpdate}, this.UserUpdateOperationCompleted, userState);
        }
        
        private void OnUserUpdateOperationCompleted(object arg) {
            if ((this.UserUpdateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UserUpdateCompleted(this, new UserUpdateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetUserByPersonalData", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public MyUser GetUserByPersonalData(string userEmail, string userPassword) {
            object[] results = this.Invoke("GetUserByPersonalData", new object[] {
                        userEmail,
                        userPassword});
            return ((MyUser)(results[0]));
        }
        
        /// <remarks/>
        public void GetUserByPersonalDataAsync(string userEmail, string userPassword) {
            this.GetUserByPersonalDataAsync(userEmail, userPassword, null);
        }
        
        /// <remarks/>
        public void GetUserByPersonalDataAsync(string userEmail, string userPassword, object userState) {
            if ((this.GetUserByPersonalDataOperationCompleted == null)) {
                this.GetUserByPersonalDataOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetUserByPersonalDataOperationCompleted);
            }
            this.InvokeAsync("GetUserByPersonalData", new object[] {
                        userEmail,
                        userPassword}, this.GetUserByPersonalDataOperationCompleted, userState);
        }
        
        private void OnGetUserByPersonalDataOperationCompleted(object arg) {
            if ((this.GetUserByPersonalDataCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetUserByPersonalDataCompleted(this, new GetUserByPersonalDataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetAllUsers", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public MyUser[] GetAllUsers() {
            object[] results = this.Invoke("GetAllUsers", new object[0]);
            return ((MyUser[])(results[0]));
        }
        
        /// <remarks/>
        public void GetAllUsersAsync() {
            this.GetAllUsersAsync(null);
        }
        
        /// <remarks/>
        public void GetAllUsersAsync(object userState) {
            if ((this.GetAllUsersOperationCompleted == null)) {
                this.GetAllUsersOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAllUsersOperationCompleted);
            }
            this.InvokeAsync("GetAllUsers", new object[0], this.GetAllUsersOperationCompleted, userState);
        }
        
        private void OnGetAllUsersOperationCompleted(object arg) {
            if ((this.GetAllUsersCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAllUsersCompleted(this, new GetAllUsersCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetUserWithEmail", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public MyUser GetUserWithEmail(string userEmail) {
            object[] results = this.Invoke("GetUserWithEmail", new object[] {
                        userEmail});
            return ((MyUser)(results[0]));
        }
        
        /// <remarks/>
        public void GetUserWithEmailAsync(string userEmail) {
            this.GetUserWithEmailAsync(userEmail, null);
        }
        
        /// <remarks/>
        public void GetUserWithEmailAsync(string userEmail, object userState) {
            if ((this.GetUserWithEmailOperationCompleted == null)) {
                this.GetUserWithEmailOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetUserWithEmailOperationCompleted);
            }
            this.InvokeAsync("GetUserWithEmail", new object[] {
                        userEmail}, this.GetUserWithEmailOperationCompleted, userState);
        }
        
        private void OnGetUserWithEmailOperationCompleted(object arg) {
            if ((this.GetUserWithEmailCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetUserWithEmailCompleted(this, new GetUserWithEmailCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/FoodItemGet", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public FoodItem FoodItemGet(int itemId) {
            object[] results = this.Invoke("FoodItemGet", new object[] {
                        itemId});
            return ((FoodItem)(results[0]));
        }
        
        /// <remarks/>
        public void FoodItemGetAsync(int itemId) {
            this.FoodItemGetAsync(itemId, null);
        }
        
        /// <remarks/>
        public void FoodItemGetAsync(int itemId, object userState) {
            if ((this.FoodItemGetOperationCompleted == null)) {
                this.FoodItemGetOperationCompleted = new System.Threading.SendOrPostCallback(this.OnFoodItemGetOperationCompleted);
            }
            this.InvokeAsync("FoodItemGet", new object[] {
                        itemId}, this.FoodItemGetOperationCompleted, userState);
        }
        
        private void OnFoodItemGetOperationCompleted(object arg) {
            if ((this.FoodItemGetCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.FoodItemGetCompleted(this, new FoodItemGetCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/FoodItemAdd", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int FoodItemAdd(FoodItem ItemToAdd) {
            object[] results = this.Invoke("FoodItemAdd", new object[] {
                        ItemToAdd});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void FoodItemAddAsync(FoodItem ItemToAdd) {
            this.FoodItemAddAsync(ItemToAdd, null);
        }
        
        /// <remarks/>
        public void FoodItemAddAsync(FoodItem ItemToAdd, object userState) {
            if ((this.FoodItemAddOperationCompleted == null)) {
                this.FoodItemAddOperationCompleted = new System.Threading.SendOrPostCallback(this.OnFoodItemAddOperationCompleted);
            }
            this.InvokeAsync("FoodItemAdd", new object[] {
                        ItemToAdd}, this.FoodItemAddOperationCompleted, userState);
        }
        
        private void OnFoodItemAddOperationCompleted(object arg) {
            if ((this.FoodItemAddCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.FoodItemAddCompleted(this, new FoodItemAddCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/FoodItemUpdate", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int FoodItemUpdate(FoodItem itemToUpdate) {
            object[] results = this.Invoke("FoodItemUpdate", new object[] {
                        itemToUpdate});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void FoodItemUpdateAsync(FoodItem itemToUpdate) {
            this.FoodItemUpdateAsync(itemToUpdate, null);
        }
        
        /// <remarks/>
        public void FoodItemUpdateAsync(FoodItem itemToUpdate, object userState) {
            if ((this.FoodItemUpdateOperationCompleted == null)) {
                this.FoodItemUpdateOperationCompleted = new System.Threading.SendOrPostCallback(this.OnFoodItemUpdateOperationCompleted);
            }
            this.InvokeAsync("FoodItemUpdate", new object[] {
                        itemToUpdate}, this.FoodItemUpdateOperationCompleted, userState);
        }
        
        private void OnFoodItemUpdateOperationCompleted(object arg) {
            if ((this.FoodItemUpdateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.FoodItemUpdateCompleted(this, new FoodItemUpdateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/FoodItemDelete", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int FoodItemDelete(FoodItem itemToDelete) {
            object[] results = this.Invoke("FoodItemDelete", new object[] {
                        itemToDelete});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void FoodItemDeleteAsync(FoodItem itemToDelete) {
            this.FoodItemDeleteAsync(itemToDelete, null);
        }
        
        /// <remarks/>
        public void FoodItemDeleteAsync(FoodItem itemToDelete, object userState) {
            if ((this.FoodItemDeleteOperationCompleted == null)) {
                this.FoodItemDeleteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnFoodItemDeleteOperationCompleted);
            }
            this.InvokeAsync("FoodItemDelete", new object[] {
                        itemToDelete}, this.FoodItemDeleteOperationCompleted, userState);
        }
        
        private void OnFoodItemDeleteOperationCompleted(object arg) {
            if ((this.FoodItemDeleteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.FoodItemDeleteCompleted(this, new FoodItemDeleteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetAllFoodItems", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public FoodItem[] GetAllFoodItems() {
            object[] results = this.Invoke("GetAllFoodItems", new object[0]);
            return ((FoodItem[])(results[0]));
        }
        
        /// <remarks/>
        public void GetAllFoodItemsAsync() {
            this.GetAllFoodItemsAsync(null);
        }
        
        /// <remarks/>
        public void GetAllFoodItemsAsync(object userState) {
            if ((this.GetAllFoodItemsOperationCompleted == null)) {
                this.GetAllFoodItemsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAllFoodItemsOperationCompleted);
            }
            this.InvokeAsync("GetAllFoodItems", new object[0], this.GetAllFoodItemsOperationCompleted, userState);
        }
        
        private void OnGetAllFoodItemsOperationCompleted(object arg) {
            if ((this.GetAllFoodItemsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAllFoodItemsCompleted(this, new GetAllFoodItemsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetFoodItemsOfCreator", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public FoodItem[] GetFoodItemsOfCreator(int userId) {
            object[] results = this.Invoke("GetFoodItemsOfCreator", new object[] {
                        userId});
            return ((FoodItem[])(results[0]));
        }
        
        /// <remarks/>
        public void GetFoodItemsOfCreatorAsync(int userId) {
            this.GetFoodItemsOfCreatorAsync(userId, null);
        }
        
        /// <remarks/>
        public void GetFoodItemsOfCreatorAsync(int userId, object userState) {
            if ((this.GetFoodItemsOfCreatorOperationCompleted == null)) {
                this.GetFoodItemsOfCreatorOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetFoodItemsOfCreatorOperationCompleted);
            }
            this.InvokeAsync("GetFoodItemsOfCreator", new object[] {
                        userId}, this.GetFoodItemsOfCreatorOperationCompleted, userState);
        }
        
        private void OnGetFoodItemsOfCreatorOperationCompleted(object arg) {
            if ((this.GetFoodItemsOfCreatorCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetFoodItemsOfCreatorCompleted(this, new GetFoodItemsOfCreatorCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetFoodItemById", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public FoodItem GetFoodItemById(int id) {
            object[] results = this.Invoke("GetFoodItemById", new object[] {
                        id});
            return ((FoodItem)(results[0]));
        }
        
        /// <remarks/>
        public void GetFoodItemByIdAsync(int id) {
            this.GetFoodItemByIdAsync(id, null);
        }
        
        /// <remarks/>
        public void GetFoodItemByIdAsync(int id, object userState) {
            if ((this.GetFoodItemByIdOperationCompleted == null)) {
                this.GetFoodItemByIdOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetFoodItemByIdOperationCompleted);
            }
            this.InvokeAsync("GetFoodItemById", new object[] {
                        id}, this.GetFoodItemByIdOperationCompleted, userState);
        }
        
        private void OnGetFoodItemByIdOperationCompleted(object arg) {
            if ((this.GetFoodItemByIdCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetFoodItemByIdCompleted(this, new GetFoodItemByIdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetAllRoles", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Roles[] GetAllRoles() {
            object[] results = this.Invoke("GetAllRoles", new object[0]);
            return ((Roles[])(results[0]));
        }
        
        /// <remarks/>
        public void GetAllRolesAsync() {
            this.GetAllRolesAsync(null);
        }
        
        /// <remarks/>
        public void GetAllRolesAsync(object userState) {
            if ((this.GetAllRolesOperationCompleted == null)) {
                this.GetAllRolesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAllRolesOperationCompleted);
            }
            this.InvokeAsync("GetAllRoles", new object[0], this.GetAllRolesOperationCompleted, userState);
        }
        
        private void OnGetAllRolesOperationCompleted(object arg) {
            if ((this.GetAllRolesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAllRolesCompleted(this, new GetAllRolesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetRoleFromId", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Roles GetRoleFromId(int roleId) {
            object[] results = this.Invoke("GetRoleFromId", new object[] {
                        roleId});
            return ((Roles)(results[0]));
        }
        
        /// <remarks/>
        public void GetRoleFromIdAsync(int roleId) {
            this.GetRoleFromIdAsync(roleId, null);
        }
        
        /// <remarks/>
        public void GetRoleFromIdAsync(int roleId, object userState) {
            if ((this.GetRoleFromIdOperationCompleted == null)) {
                this.GetRoleFromIdOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetRoleFromIdOperationCompleted);
            }
            this.InvokeAsync("GetRoleFromId", new object[] {
                        roleId}, this.GetRoleFromIdOperationCompleted, userState);
        }
        
        private void OnGetRoleFromIdOperationCompleted(object arg) {
            if ((this.GetRoleFromIdCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetRoleFromIdCompleted(this, new GetRoleFromIdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/RoleUpdate", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int RoleUpdate(Roles role) {
            object[] results = this.Invoke("RoleUpdate", new object[] {
                        role});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void RoleUpdateAsync(Roles role) {
            this.RoleUpdateAsync(role, null);
        }
        
        /// <remarks/>
        public void RoleUpdateAsync(Roles role, object userState) {
            if ((this.RoleUpdateOperationCompleted == null)) {
                this.RoleUpdateOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRoleUpdateOperationCompleted);
            }
            this.InvokeAsync("RoleUpdate", new object[] {
                        role}, this.RoleUpdateOperationCompleted, userState);
        }
        
        private void OnRoleUpdateOperationCompleted(object arg) {
            if ((this.RoleUpdateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RoleUpdateCompleted(this, new RoleUpdateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/RoleAdd", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int RoleAdd(Roles role) {
            object[] results = this.Invoke("RoleAdd", new object[] {
                        role});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void RoleAddAsync(Roles role) {
            this.RoleAddAsync(role, null);
        }
        
        /// <remarks/>
        public void RoleAddAsync(Roles role, object userState) {
            if ((this.RoleAddOperationCompleted == null)) {
                this.RoleAddOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRoleAddOperationCompleted);
            }
            this.InvokeAsync("RoleAdd", new object[] {
                        role}, this.RoleAddOperationCompleted, userState);
        }
        
        private void OnRoleAddOperationCompleted(object arg) {
            if ((this.RoleAddCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RoleAddCompleted(this, new RoleAddCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AddItemToOrder", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void AddItemToOrder(ref OrderedItems orderedItems, ref FoodItem item) {
            object[] results = this.Invoke("AddItemToOrder", new object[] {
                        orderedItems,
                        item});
            orderedItems = ((OrderedItems)(results[0]));
            item = ((FoodItem)(results[1]));
        }
        
        /// <remarks/>
        public void AddItemToOrderAsync(OrderedItems orderedItems, FoodItem item) {
            this.AddItemToOrderAsync(orderedItems, item, null);
        }
        
        /// <remarks/>
        public void AddItemToOrderAsync(OrderedItems orderedItems, FoodItem item, object userState) {
            if ((this.AddItemToOrderOperationCompleted == null)) {
                this.AddItemToOrderOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAddItemToOrderOperationCompleted);
            }
            this.InvokeAsync("AddItemToOrder", new object[] {
                        orderedItems,
                        item}, this.AddItemToOrderOperationCompleted, userState);
        }
        
        private void OnAddItemToOrderOperationCompleted(object arg) {
            if ((this.AddItemToOrderCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AddItemToOrderCompleted(this, new AddItemToOrderCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AddOrderToHistory", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void AddOrderToHistory(ref Orders orderHistory, ref OrderedItems order) {
            object[] results = this.Invoke("AddOrderToHistory", new object[] {
                        orderHistory,
                        order});
            orderHistory = ((Orders)(results[0]));
            order = ((OrderedItems)(results[1]));
        }
        
        /// <remarks/>
        public void AddOrderToHistoryAsync(Orders orderHistory, OrderedItems order) {
            this.AddOrderToHistoryAsync(orderHistory, order, null);
        }
        
        /// <remarks/>
        public void AddOrderToHistoryAsync(Orders orderHistory, OrderedItems order, object userState) {
            if ((this.AddOrderToHistoryOperationCompleted == null)) {
                this.AddOrderToHistoryOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAddOrderToHistoryOperationCompleted);
            }
            this.InvokeAsync("AddOrderToHistory", new object[] {
                        orderHistory,
                        order}, this.AddOrderToHistoryOperationCompleted, userState);
        }
        
        private void OnAddOrderToHistoryOperationCompleted(object arg) {
            if ((this.AddOrderToHistoryCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AddOrderToHistoryCompleted(this, new AddOrderToHistoryCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UpdateOrderedItems", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int UpdateOrderedItems(OrderedItems orderedItems) {
            object[] results = this.Invoke("UpdateOrderedItems", new object[] {
                        orderedItems});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void UpdateOrderedItemsAsync(OrderedItems orderedItems) {
            this.UpdateOrderedItemsAsync(orderedItems, null);
        }
        
        /// <remarks/>
        public void UpdateOrderedItemsAsync(OrderedItems orderedItems, object userState) {
            if ((this.UpdateOrderedItemsOperationCompleted == null)) {
                this.UpdateOrderedItemsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateOrderedItemsOperationCompleted);
            }
            this.InvokeAsync("UpdateOrderedItems", new object[] {
                        orderedItems}, this.UpdateOrderedItemsOperationCompleted, userState);
        }
        
        private void OnUpdateOrderedItemsOperationCompleted(object arg) {
            if ((this.UpdateOrderedItemsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateOrderedItemsCompleted(this, new UpdateOrderedItemsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UpdateOrders", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int UpdateOrders(Orders order) {
            object[] results = this.Invoke("UpdateOrders", new object[] {
                        order});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void UpdateOrdersAsync(Orders order) {
            this.UpdateOrdersAsync(order, null);
        }
        
        /// <remarks/>
        public void UpdateOrdersAsync(Orders order, object userState) {
            if ((this.UpdateOrdersOperationCompleted == null)) {
                this.UpdateOrdersOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateOrdersOperationCompleted);
            }
            this.InvokeAsync("UpdateOrders", new object[] {
                        order}, this.UpdateOrdersOperationCompleted, userState);
        }
        
        private void OnUpdateOrdersOperationCompleted(object arg) {
            if ((this.UpdateOrdersCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateOrdersCompleted(this, new UpdateOrdersCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AddOrderedItem", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int AddOrderedItem(OrderedItems orderedItems) {
            object[] results = this.Invoke("AddOrderedItem", new object[] {
                        orderedItems});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void AddOrderedItemAsync(OrderedItems orderedItems) {
            this.AddOrderedItemAsync(orderedItems, null);
        }
        
        /// <remarks/>
        public void AddOrderedItemAsync(OrderedItems orderedItems, object userState) {
            if ((this.AddOrderedItemOperationCompleted == null)) {
                this.AddOrderedItemOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAddOrderedItemOperationCompleted);
            }
            this.InvokeAsync("AddOrderedItem", new object[] {
                        orderedItems}, this.AddOrderedItemOperationCompleted, userState);
        }
        
        private void OnAddOrderedItemOperationCompleted(object arg) {
            if ((this.AddOrderedItemCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AddOrderedItemCompleted(this, new AddOrderedItemCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AddOrders", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int AddOrders(Orders order) {
            object[] results = this.Invoke("AddOrders", new object[] {
                        order});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void AddOrdersAsync(Orders order) {
            this.AddOrdersAsync(order, null);
        }
        
        /// <remarks/>
        public void AddOrdersAsync(Orders order, object userState) {
            if ((this.AddOrdersOperationCompleted == null)) {
                this.AddOrdersOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAddOrdersOperationCompleted);
            }
            this.InvokeAsync("AddOrders", new object[] {
                        order}, this.AddOrdersOperationCompleted, userState);
        }
        
        private void OnAddOrdersOperationCompleted(object arg) {
            if ((this.AddOrdersCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AddOrdersCompleted(this, new AddOrdersCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class MyUser {
        
        private int userIdField;
        
        private string userNameField;
        
        private string userEmailField;
        
        private string userPasswordField;
        
        private Roles roleTagField;
        
        private Orders orderHistoryField;
        
        /// <remarks/>
        public int UserId {
            get {
                return this.userIdField;
            }
            set {
                this.userIdField = value;
            }
        }
        
        /// <remarks/>
        public string UserName {
            get {
                return this.userNameField;
            }
            set {
                this.userNameField = value;
            }
        }
        
        /// <remarks/>
        public string UserEmail {
            get {
                return this.userEmailField;
            }
            set {
                this.userEmailField = value;
            }
        }
        
        /// <remarks/>
        public string UserPassword {
            get {
                return this.userPasswordField;
            }
            set {
                this.userPasswordField = value;
            }
        }
        
        /// <remarks/>
        public Roles RoleTag {
            get {
                return this.roleTagField;
            }
            set {
                this.roleTagField = value;
            }
        }
        
        /// <remarks/>
        public Orders OrderHistory {
            get {
                return this.orderHistoryField;
            }
            set {
                this.orderHistoryField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Roles {
        
        private int roleIdField;
        
        private string roleTagField;
        
        /// <remarks/>
        public int RoleId {
            get {
                return this.roleIdField;
            }
            set {
                this.roleIdField = value;
            }
        }
        
        /// <remarks/>
        public string RoleTag {
            get {
                return this.roleTagField;
            }
            set {
                this.roleTagField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class FoodItem {
        
        private int itemIdField;
        
        private double itemPriceField;
        
        private string itemDescriptionField;
        
        private int userIdField;
        
        /// <remarks/>
        public int ItemId {
            get {
                return this.itemIdField;
            }
            set {
                this.itemIdField = value;
            }
        }
        
        /// <remarks/>
        public double ItemPrice {
            get {
                return this.itemPriceField;
            }
            set {
                this.itemPriceField = value;
            }
        }
        
        /// <remarks/>
        public string ItemDescription {
            get {
                return this.itemDescriptionField;
            }
            set {
                this.itemDescriptionField = value;
            }
        }
        
        /// <remarks/>
        public int UserId {
            get {
                return this.userIdField;
            }
            set {
                this.userIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class OrderedItems {
        
        private int orderIdField;
        
        private FoodItem[] foodItemsField;
        
        private int[] foodAmountsField;
        
        private System.DateTime orderDateField;
        
        /// <remarks/>
        public int OrderId {
            get {
                return this.orderIdField;
            }
            set {
                this.orderIdField = value;
            }
        }
        
        /// <remarks/>
        public FoodItem[] FoodItems {
            get {
                return this.foodItemsField;
            }
            set {
                this.foodItemsField = value;
            }
        }
        
        /// <remarks/>
        public int[] FoodAmounts {
            get {
                return this.foodAmountsField;
            }
            set {
                this.foodAmountsField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime OrderDate {
            get {
                return this.orderDateField;
            }
            set {
                this.orderDateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Orders {
        
        private int userIdField;
        
        private OrderedItems[] orderListField;
        
        /// <remarks/>
        public int UserId {
            get {
                return this.userIdField;
            }
            set {
                this.userIdField = value;
            }
        }
        
        /// <remarks/>
        public OrderedItems[] OrderList {
            get {
                return this.orderListField;
            }
            set {
                this.orderListField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9221.0")]
    public delegate void UserGetCompletedEventHandler(object sender, UserGetCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9221.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UserGetCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UserGetCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public MyUser Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((MyUser)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9221.0")]
    public delegate void UserAddCompletedEventHandler(object sender, UserAddCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9221.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UserAddCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UserAddCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9221.0")]
    public delegate void UserDeleteCompletedEventHandler(object sender, UserDeleteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9221.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UserDeleteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UserDeleteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9221.0")]
    public delegate void UserUpdateCompletedEventHandler(object sender, UserUpdateCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9221.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UserUpdateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UserUpdateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9221.0")]
    public delegate void GetUserByPersonalDataCompletedEventHandler(object sender, GetUserByPersonalDataCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9221.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetUserByPersonalDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetUserByPersonalDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public MyUser Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((MyUser)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9221.0")]
    public delegate void GetAllUsersCompletedEventHandler(object sender, GetAllUsersCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9221.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAllUsersCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAllUsersCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public MyUser[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((MyUser[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9221.0")]
    public delegate void GetUserWithEmailCompletedEventHandler(object sender, GetUserWithEmailCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9221.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetUserWithEmailCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetUserWithEmailCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public MyUser Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((MyUser)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9221.0")]
    public delegate void FoodItemGetCompletedEventHandler(object sender, FoodItemGetCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9221.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class FoodItemGetCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal FoodItemGetCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public FoodItem Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((FoodItem)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9221.0")]
    public delegate void FoodItemAddCompletedEventHandler(object sender, FoodItemAddCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9221.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class FoodItemAddCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal FoodItemAddCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9221.0")]
    public delegate void FoodItemUpdateCompletedEventHandler(object sender, FoodItemUpdateCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9221.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class FoodItemUpdateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal FoodItemUpdateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9221.0")]
    public delegate void FoodItemDeleteCompletedEventHandler(object sender, FoodItemDeleteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9221.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class FoodItemDeleteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal FoodItemDeleteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9221.0")]
    public delegate void GetAllFoodItemsCompletedEventHandler(object sender, GetAllFoodItemsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9221.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAllFoodItemsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAllFoodItemsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public FoodItem[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((FoodItem[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9221.0")]
    public delegate void GetFoodItemsOfCreatorCompletedEventHandler(object sender, GetFoodItemsOfCreatorCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9221.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetFoodItemsOfCreatorCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetFoodItemsOfCreatorCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public FoodItem[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((FoodItem[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9221.0")]
    public delegate void GetFoodItemByIdCompletedEventHandler(object sender, GetFoodItemByIdCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9221.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetFoodItemByIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetFoodItemByIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public FoodItem Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((FoodItem)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9221.0")]
    public delegate void GetAllRolesCompletedEventHandler(object sender, GetAllRolesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9221.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAllRolesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAllRolesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Roles[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Roles[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9221.0")]
    public delegate void GetRoleFromIdCompletedEventHandler(object sender, GetRoleFromIdCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9221.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetRoleFromIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetRoleFromIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Roles Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Roles)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9221.0")]
    public delegate void RoleUpdateCompletedEventHandler(object sender, RoleUpdateCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9221.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RoleUpdateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RoleUpdateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9221.0")]
    public delegate void RoleAddCompletedEventHandler(object sender, RoleAddCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9221.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RoleAddCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RoleAddCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9221.0")]
    public delegate void AddItemToOrderCompletedEventHandler(object sender, AddItemToOrderCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9221.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AddItemToOrderCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AddItemToOrderCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public OrderedItems orderedItems {
            get {
                this.RaiseExceptionIfNecessary();
                return ((OrderedItems)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public FoodItem item {
            get {
                this.RaiseExceptionIfNecessary();
                return ((FoodItem)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9221.0")]
    public delegate void AddOrderToHistoryCompletedEventHandler(object sender, AddOrderToHistoryCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9221.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AddOrderToHistoryCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AddOrderToHistoryCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Orders orderHistory {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Orders)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public OrderedItems order {
            get {
                this.RaiseExceptionIfNecessary();
                return ((OrderedItems)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9221.0")]
    public delegate void UpdateOrderedItemsCompletedEventHandler(object sender, UpdateOrderedItemsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9221.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateOrderedItemsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateOrderedItemsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9221.0")]
    public delegate void UpdateOrdersCompletedEventHandler(object sender, UpdateOrdersCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9221.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateOrdersCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateOrdersCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9221.0")]
    public delegate void AddOrderedItemCompletedEventHandler(object sender, AddOrderedItemCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9221.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AddOrderedItemCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AddOrderedItemCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9221.0")]
    public delegate void AddOrdersCompletedEventHandler(object sender, AddOrdersCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9221.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AddOrdersCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AddOrdersCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591